server:
  port: 80

spring:
  datasource:
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: PUBLIC-API-DB
      schema: test_schema1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.223:5432/itbiz?useUnicode=yes&characterEncoding=UTF-8
    username: itbiz
    password: itbiz2021


  jpa.hibernate.ddl-auto: none
  jpa.properties.hibernate.jdbc.time_zone: Asia/Seoul
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  jpa.show-sql: true  # SQL 로그 출력 여부
  jpa.properties.hibernate.format_sql: true  # SQL 출력 가독성 여부
  jpa.properties.hibernate.use_sql_comments: true  # SQL 문 이외의 추가 정보 출력 여부
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
  # JSON RETURN시 null값 항목 제외
  jackson.default-property-inclusion: NON_NULL